= Feelings Guide

Simple app that helps people log their feelings.

== Release

.Example:
----
git tag -a 2.0.0 -m "Release 2.0.0"
git tag
git push origin --tags
----

== Developer setup

- Install Android Studio
- In Android Studio (Android SDK > SDK Tools), install `Android SDK Command-line Tools`

== Manual testing

Install on a virtual or physical device from Android Studio.

== Automated UI testing

Run scripts from `scripts` directory. In desired execution order:

- `avd-create.sh` - downloads images and creates a bunch of virtual devices
** At the very first execution, you need to accept licenses interactively.
** Sleep time in the script is to let each device finish setting up. Actual sleep time depends on a number of factors. Current sleep time is enough on my laptop, but you may need to increase it on another host.
** If one of the devices can't finish setup in that time, you may have to manually boot into it via Device Manager GUI from Android Studio to let it finish
- `avd-setup.sh` prepares all virtual devices for UI tests:
** turn off animation
** turn off keyboard auto-correction - **have to do that manually** on each device for now. didn't find a way to do it programmatically
- `app-install.sh` installs the app on all virtual devices.
- `run-tests-on-all-devices.sh` runs UI tests on each virtual device sequentially.
- `app-uninstall.sh` uninstalls the app from all virtual devices to test fresh install.
- `avd-delete.sh` deletes all virtual devices, if they are not needed anymore or to troubleshoot.

== App version to DB version mapping

|===
|App version code |App version name |DB version

|9 |2.3.0 |3
|8 |2.2.2 |3
|7 |2.2.1 |3
|6 |2.2.0 |3
|5 |2.1.1 |3
|4 |2.1.0 |3
|3 |2.0.0 |3
|2 |1.1.0 |2
|1 |1.0.0 |1
|===

== Debugging on a virtual device

=== Get the DB from virtual device

----
adb shell
su
chmod -R 777 /data
# ctrl+D (exit shell) twice
adb root
cd to_intended_folder
adb pull /data/data/feelings.guide/databases/FeelingsGuide.db
----

